// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddConsumableToPlayerHandler(ReducerEventContext ctx, uint itemId);
        public event AddConsumableToPlayerHandler? OnAddConsumableToPlayer;

        public void AddConsumableToPlayer(uint itemId)
        {
            conn.InternalCallReducer(new Reducer.AddConsumableToPlayer(itemId), this.SetCallReducerFlags.AddConsumableToPlayerFlags);
        }

        public bool InvokeAddConsumableToPlayer(ReducerEventContext ctx, Reducer.AddConsumableToPlayer args)
        {
            if (OnAddConsumableToPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddConsumableToPlayer(
                ctx,
                args.ItemId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddConsumableToPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "itemId")]
            public uint ItemId;

            public AddConsumableToPlayer(uint ItemId)
            {
                this.ItemId = ItemId;
            }

            public AddConsumableToPlayer()
            {
            }

            string IReducerArgs.ReducerName => "AddConsumableToPlayer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddConsumableToPlayerFlags;
        public void AddConsumableToPlayer(CallReducerFlags flags) => AddConsumableToPlayerFlags = flags;
    }
}
