// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddItemHandler(ReducerEventContext ctx, uint id);
        public event AddItemHandler? OnAddItem;

        public void AddItem(uint id)
        {
            conn.InternalCallReducer(new Reducer.AddItem(id), this.SetCallReducerFlags.AddItemFlags);
        }

        public bool InvokeAddItem(ReducerEventContext ctx, Reducer.AddItem args)
        {
            if (OnAddItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddItem(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "_id")]
            public uint Id;

            public AddItem(uint Id)
            {
                this.Id = Id;
            }

            public AddItem()
            {
            }

            string IReducerArgs.ReducerName => "AddItem";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddItemFlags;
        public void AddItem(CallReducerFlags flags) => AddItemFlags = flags;
    }
}
