// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddStationWithMoneyHandler(ReducerEventContext ctx, string id, string name, uint money);
        public event AddStationWithMoneyHandler? OnAddStationWithMoney;

        public void AddStationWithMoney(string id, string name, uint money)
        {
            conn.InternalCallReducer(new Reducer.AddStationWithMoney(id, name, money), this.SetCallReducerFlags.AddStationWithMoneyFlags);
        }

        public bool InvokeAddStationWithMoney(ReducerEventContext ctx, Reducer.AddStationWithMoney args)
        {
            if (OnAddStationWithMoney == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddStationWithMoney(
                ctx,
                args.Id,
                args.Name,
                args.Money
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddStationWithMoney : Reducer, IReducerArgs
        {
            [DataMember(Name = "_id")]
            public string Id;
            [DataMember(Name = "_name")]
            public string Name;
            [DataMember(Name = "_money")]
            public uint Money;

            public AddStationWithMoney(
                string Id,
                string Name,
                uint Money
            )
            {
                this.Id = Id;
                this.Name = Name;
                this.Money = Money;
            }

            public AddStationWithMoney()
            {
                this.Id = "";
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "AddStationWithMoney";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddStationWithMoneyFlags;
        public void AddStationWithMoney(CallReducerFlags flags) => AddStationWithMoneyFlags = flags;
    }
}
