// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteTrainHandler(ReducerEventContext ctx, string id);
        public event DeleteTrainHandler? OnDeleteTrain;

        public void DeleteTrain(string id)
        {
            conn.InternalCallReducer(new Reducer.DeleteTrain(id), this.SetCallReducerFlags.DeleteTrainFlags);
        }

        public bool InvokeDeleteTrain(ReducerEventContext ctx, Reducer.DeleteTrain args)
        {
            if (OnDeleteTrain == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteTrain(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteTrain : Reducer, IReducerArgs
        {
            [DataMember(Name = "_id")]
            public string Id;

            public DeleteTrain(string Id)
            {
                this.Id = Id;
            }

            public DeleteTrain()
            {
                this.Id = "";
            }

            string IReducerArgs.ReducerName => "DeleteTrain";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteTrainFlags;
        public void DeleteTrain(CallReducerFlags flags) => DeleteTrainFlags = flags;
    }
}
