// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteItemHandler(ReducerEventContext ctx, uint id);
        public event DeleteItemHandler? OnDeleteItem;

        public void DeleteItem(uint id)
        {
            conn.InternalCallReducer(new Reducer.DeleteItem(id), this.SetCallReducerFlags.DeleteItemFlags);
        }

        public bool InvokeDeleteItem(ReducerEventContext ctx, Reducer.DeleteItem args)
        {
            if (OnDeleteItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteItem(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "_id")]
            public uint Id;

            public DeleteItem(uint Id)
            {
                this.Id = Id;
            }

            public DeleteItem()
            {
            }

            string IReducerArgs.ReducerName => "DeleteItem";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteItemFlags;
        public void DeleteItem(CallReducerFlags flags) => DeleteItemFlags = flags;
    }
}
