// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnterTheTrainHandler(ReducerEventContext ctx, string id, string fromStationId, string toStationId, string playerId, uint money);
        public event EnterTheTrainHandler? OnEnterTheTrain;

        public void EnterTheTrain(string id, string fromStationId, string toStationId, string playerId, uint money)
        {
            conn.InternalCallReducer(new Reducer.EnterTheTrain(id, fromStationId, toStationId, playerId, money), this.SetCallReducerFlags.EnterTheTrainFlags);
        }

        public bool InvokeEnterTheTrain(ReducerEventContext ctx, Reducer.EnterTheTrain args)
        {
            if (OnEnterTheTrain == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnterTheTrain(
                ctx,
                args.Id,
                args.FromStationId,
                args.ToStationId,
                args.PlayerId,
                args.Money
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnterTheTrain : Reducer, IReducerArgs
        {
            [DataMember(Name = "_id")]
            public string Id;
            [DataMember(Name = "_from_station_id")]
            public string FromStationId;
            [DataMember(Name = "_to_station_id")]
            public string ToStationId;
            [DataMember(Name = "_player_id")]
            public string PlayerId;
            [DataMember(Name = "_money")]
            public uint Money;

            public EnterTheTrain(
                string Id,
                string FromStationId,
                string ToStationId,
                string PlayerId,
                uint Money
            )
            {
                this.Id = Id;
                this.FromStationId = FromStationId;
                this.ToStationId = ToStationId;
                this.PlayerId = PlayerId;
                this.Money = Money;
            }

            public EnterTheTrain()
            {
                this.Id = "";
                this.FromStationId = "";
                this.ToStationId = "";
                this.PlayerId = "";
            }

            string IReducerArgs.ReducerName => "EnterTheTrain";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EnterTheTrainFlags;
        public void EnterTheTrain(CallReducerFlags flags) => EnterTheTrainFlags = flags;
    }
}
