// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EquipWeaponHandler(ReducerEventContext ctx, uint itemId, string playerId);
        public event EquipWeaponHandler? OnEquipWeapon;

        public void EquipWeapon(uint itemId, string playerId)
        {
            conn.InternalCallReducer(new Reducer.EquipWeapon(itemId, playerId), this.SetCallReducerFlags.EquipWeaponFlags);
        }

        public bool InvokeEquipWeapon(ReducerEventContext ctx, Reducer.EquipWeapon args)
        {
            if (OnEquipWeapon == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEquipWeapon(
                ctx,
                args.ItemId,
                args.PlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EquipWeapon : Reducer, IReducerArgs
        {
            [DataMember(Name = "itemId")]
            public uint ItemId;
            [DataMember(Name = "player_id")]
            public string PlayerId;

            public EquipWeapon(
                uint ItemId,
                string PlayerId
            )
            {
                this.ItemId = ItemId;
                this.PlayerId = PlayerId;
            }

            public EquipWeapon()
            {
                this.PlayerId = "";
            }

            string IReducerArgs.ReducerName => "EquipWeapon";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EquipWeaponFlags;
        public void EquipWeapon(CallReducerFlags flags) => EquipWeaponFlags = flags;
    }
}
