// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetConsumablesToPlayerHandler(ReducerEventContext ctx, string playerId, System.Collections.Generic.List<Item> consumables);
        public event SetConsumablesToPlayerHandler? OnSetConsumablesToPlayer;

        public void SetConsumablesToPlayer(string playerId, System.Collections.Generic.List<Item> consumables)
        {
            conn.InternalCallReducer(new Reducer.SetConsumablesToPlayer(playerId, consumables), this.SetCallReducerFlags.SetConsumablesToPlayerFlags);
        }

        public bool InvokeSetConsumablesToPlayer(ReducerEventContext ctx, Reducer.SetConsumablesToPlayer args)
        {
            if (OnSetConsumablesToPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetConsumablesToPlayer(
                ctx,
                args.PlayerId,
                args.Consumables
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetConsumablesToPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public string PlayerId;
            [DataMember(Name = "consumables")]
            public System.Collections.Generic.List<Item> Consumables;

            public SetConsumablesToPlayer(
                string PlayerId,
                System.Collections.Generic.List<Item> Consumables
            )
            {
                this.PlayerId = PlayerId;
                this.Consumables = Consumables;
            }

            public SetConsumablesToPlayer()
            {
                this.PlayerId = "";
                this.Consumables = new();
            }

            string IReducerArgs.ReducerName => "SetConsumablesToPlayer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetConsumablesToPlayerFlags;
        public void SetConsumablesToPlayer(CallReducerFlags flags) => SetConsumablesToPlayerFlags = flags;
    }
}
