// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetInventoryToPlayerHandler(ReducerEventContext ctx, string playerId, System.Collections.Generic.List<Item> items);
        public event SetInventoryToPlayerHandler? OnSetInventoryToPlayer;

        public void SetInventoryToPlayer(string playerId, System.Collections.Generic.List<Item> items)
        {
            conn.InternalCallReducer(new Reducer.SetInventoryToPlayer(playerId, items), this.SetCallReducerFlags.SetInventoryToPlayerFlags);
        }

        public bool InvokeSetInventoryToPlayer(ReducerEventContext ctx, Reducer.SetInventoryToPlayer args)
        {
            if (OnSetInventoryToPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetInventoryToPlayer(
                ctx,
                args.PlayerId,
                args.Items
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetInventoryToPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public string PlayerId;
            [DataMember(Name = "items")]
            public System.Collections.Generic.List<Item> Items;

            public SetInventoryToPlayer(
                string PlayerId,
                System.Collections.Generic.List<Item> Items
            )
            {
                this.PlayerId = PlayerId;
                this.Items = Items;
            }

            public SetInventoryToPlayer()
            {
                this.PlayerId = "";
                this.Items = new();
            }

            string IReducerArgs.ReducerName => "SetInventoryToPlayer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetInventoryToPlayerFlags;
        public void SetInventoryToPlayer(CallReducerFlags flags) => SetInventoryToPlayerFlags = flags;
    }
}
