// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPlayerMoneyHandler(ReducerEventContext ctx, string playerId, uint playerMoney);
        public event SetPlayerMoneyHandler? OnSetPlayerMoney;

        public void SetPlayerMoney(string playerId, uint playerMoney)
        {
            conn.InternalCallReducer(new Reducer.SetPlayerMoney(playerId, playerMoney), this.SetCallReducerFlags.SetPlayerMoneyFlags);
        }

        public bool InvokeSetPlayerMoney(ReducerEventContext ctx, Reducer.SetPlayerMoney args)
        {
            if (OnSetPlayerMoney == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetPlayerMoney(
                ctx,
                args.PlayerId,
                args.PlayerMoney
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPlayerMoney : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public string PlayerId;
            [DataMember(Name = "player_money")]
            public uint PlayerMoney;

            public SetPlayerMoney(
                string PlayerId,
                uint PlayerMoney
            )
            {
                this.PlayerId = PlayerId;
                this.PlayerMoney = PlayerMoney;
            }

            public SetPlayerMoney()
            {
                this.PlayerId = "";
            }

            string IReducerArgs.ReducerName => "SetPlayerMoney";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetPlayerMoneyFlags;
        public void SetPlayerMoney(CallReducerFlags flags) => SetPlayerMoneyFlags = flags;
    }
}
