// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPlayerClassHandler(ReducerEventContext ctx, string playerId, string playerClass);
        public event SetPlayerClassHandler? OnSetPlayerClass;

        public void SetPlayerClass(string playerId, string playerClass)
        {
            conn.InternalCallReducer(new Reducer.SetPlayerClass(playerId, playerClass), this.SetCallReducerFlags.SetPlayerClassFlags);
        }

        public bool InvokeSetPlayerClass(ReducerEventContext ctx, Reducer.SetPlayerClass args)
        {
            if (OnSetPlayerClass == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetPlayerClass(
                ctx,
                args.PlayerId,
                args.PlayerClass
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPlayerClass : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public string PlayerId;
            [DataMember(Name = "player_class")]
            public string PlayerClass;

            public SetPlayerClass(
                string PlayerId,
                string PlayerClass
            )
            {
                this.PlayerId = PlayerId;
                this.PlayerClass = PlayerClass;
            }

            public SetPlayerClass()
            {
                this.PlayerId = "";
                this.PlayerClass = "";
            }

            string IReducerArgs.ReducerName => "SetPlayerClass";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetPlayerClassFlags;
        public void SetPlayerClass(CallReducerFlags flags) => SetPlayerClassFlags = flags;
    }
}
