// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetTrainStartedHandler(ReducerEventContext ctx, string from, string to, bool started);
        public event SetTrainStartedHandler? OnSetTrainStarted;

        public void SetTrainStarted(string from, string to, bool started)
        {
            conn.InternalCallReducer(new Reducer.SetTrainStarted(from, to, started), this.SetCallReducerFlags.SetTrainStartedFlags);
        }

        public bool InvokeSetTrainStarted(ReducerEventContext ctx, Reducer.SetTrainStarted args)
        {
            if (OnSetTrainStarted == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetTrainStarted(
                ctx,
                args.From,
                args.To,
                args.Started
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetTrainStarted : Reducer, IReducerArgs
        {
            [DataMember(Name = "from")]
            public string From;
            [DataMember(Name = "to")]
            public string To;
            [DataMember(Name = "_started")]
            public bool Started;

            public SetTrainStarted(
                string From,
                string To,
                bool Started
            )
            {
                this.From = From;
                this.To = To;
                this.Started = Started;
            }

            public SetTrainStarted()
            {
                this.From = "";
                this.To = "";
            }

            string IReducerArgs.ReducerName => "SetTrainStarted";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetTrainStartedFlags;
        public void SetTrainStarted(CallReducerFlags flags) => SetTrainStartedFlags = flags;
    }
}
