// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TrainHandle : RemoteTableHandle<EventContext, Train>
        {
            protected override string RemoteTableName => "train";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Train row) => row.Id;

                public IdUniqueIndex(TrainHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TrainHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Train row) => row.Id;
        }

        public readonly TrainHandle Train;
    }
}
