// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Station
    {
        [DataMember(Name = "mvg_id")]
        public string MvgId;
        [DataMember(Name = "game_id")]
        public string GameId;
        [DataMember(Name = "money")]
        public uint Money;

        public Station(
            string MvgId,
            string GameId,
            uint Money
        )
        {
            this.MvgId = MvgId;
            this.GameId = GameId;
            this.Money = Money;
        }

        public Station()
        {
            this.MvgId = "";
            this.GameId = "";
        }
    }
}
