// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Train
    {
        [DataMember(Name = "id")]
        public string Id;
        [DataMember(Name = "started")]
        public bool Started;
        [DataMember(Name = "from_station_id")]
        public string FromStationId;
        [DataMember(Name = "to_station_id")]
        public string ToStationId;
        [DataMember(Name = "money")]
        public uint Money;
        [DataMember(Name = "player_ids")]
        public System.Collections.Generic.List<string> PlayerIds;

        public Train(
            string Id,
            bool Started,
            string FromStationId,
            string ToStationId,
            uint Money,
            System.Collections.Generic.List<string> PlayerIds
        )
        {
            this.Id = Id;
            this.Started = Started;
            this.FromStationId = FromStationId;
            this.ToStationId = ToStationId;
            this.Money = Money;
            this.PlayerIds = PlayerIds;
        }

        public Train()
        {
            this.Id = "";
            this.FromStationId = "";
            this.ToStationId = "";
            this.PlayerIds = new();
        }
    }
}
